services:
    web:
        build: .
        container_name: "php74-1"
        volumes:
            - "./html/:/var/www/html"
        privileged: true
        ports:
            - "80:80"
        depends_on:
            - mysql
    mysql:
        build: ./mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=test_user
            - MYSQL_PASSWORD=test_password
        ports:
            - "4306:3306"
        container_name: mysql8-1
